---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: meetingserver-tls
  namespace: openeuler-meetingserver
spec:
  name: meetingserver-tls
  keysMap:
    ca.crt:
      path: secrets/data/openeuler/openeuler-openatom-cn-tls
      key: server.crt
    tls.crt:
      path: secrets/data/openeuler/openeuler-openatom-cn-tls
      key: server.crt
    tls.key:
      path: secrets/data/openeuler/openeuler-openatom-cn-tls
      key: server.key
