apiVersion: v1
kind: ConfigMap
metadata:
  name: message-server-configmap
  namespace: openeuler-software-pkg
data:
  config.yaml: |
    kafka:
      address: "${KAFKA_ADDRESS}"
    group_name: software-package
    topics_to_subscribe:
      software_pkg_ci_checking: software_pkg_ci_checking
      software_pkg_ci_checked: software_pkg_ci_checked
      software_pkg_code_saved: software_pkg_code_saved
      software_pkg_initialized: software_pkg_initialized
      software_pkg_repo_created: software_pkg_repo_created
      software_pkg_already_existed: software_pkg_already_existed
    topics_to_notify:
      already_closed_software_pkg: software_pkg_already_closed
      indirectly_approved_software_pkg: software_pkg_indirectly_approved
    postgresql:
      db:
        host: "${DB_HOST}"
        port: 5432
        user: "${DB_USER}"
        pwd: "${DB_PWD}"
        name: "${DB_NAME}"
        life: 2
        max_conn: 500
        max_idle: 250
      table:
        software_pkg_basic: software_pkg_basic
        review_comment: review_comment
        translation_comment: translation_comment
    sig:
      read_url: https://omapi.osinfra.cn/query/sig/scoreAll?community=openeuler
      interval: 1
    pkg_manager:
      access_token: "${ACCESS_TOKEN}"
      existing_pkgs:
        meta_data_endpoint: https://omapi.osinfra.cn/query/sig/info?community=openeuler&search=fuzzy&repo=src-openeuler/
        org_of_pkg_repo: src-openeuler
        default_info:
          platform: gitee
          importer_name: software-pkg-robot
          importer_email: software@openeuler.org
          reason_to_import: "add software package to openeuler"
    software_pkg:
      domain_primitive:
        supported_platforms:
          - gitee
          - github
        local_platform: gitee
      min_num_of_approvers: 2
      max_length_of_review_comment: 1000
    encryption:
      encryption_key: "${ENCRYPTION_KEY}"
    ci:
      ci_endpoint: https://openeulerjenkins.osinfra.cn/generic-webhook-trigger/invoke