apiVersion: v1
kind: ConfigMap
metadata:
  name: robot-configmap
  namespace: openeuler-software-pkg
data:
  config.yaml: |
    code:
      pkg_src_org: src-openeuler
      watch:
        interval: 180
        loop_times: 3
      robot:
        username: "${OPENEULER_ROBOT_NAME}"
        token: "${OPENEULER_ROBOT_TOKEN}"
      ci_repo:
        repo: software-package-server
        link: https://gitee.com/I-am-a-robot/software-package-server.git
    kafka:
      address: "${KAFKA_ADDRESS}"
      version: "${KAFKA_VERSION}"
    message_server:
      group_name: software-package
      topics:
        push_code: software_pkg_initialized
      message:
        topics_to_notify:
          pushed_code: software_pkg_repo_code_pushed
    om_api:
      app_id: "${APP_ID}"
      app_secret: "${APP_SECRET}"
      token_endpoint: https://omapi.osinfra.cn/oneid/manager/token
      user_endpoint: https://omapi.osinfra.cn/oneid/manager/getuserinfo?username=